#!/usr/bin/env zsh

# Install command-line tools using Homebrew
run_brew() {
	# Make sure we’re using the latest Homebrew
	brew update

	brew bundle

	# Remove outdated versions from the cellar
	e_process "Clean up brew"
	brew cleanup
}
