#!/usr/bin/env zsh

dotfiles=(.ackrc .aliases .editorconfig .exports .functions .gitattributes .gitconfig .gitignore .inputrc .nanorc .oh-my-zsh-config .osx .vim .vimrc .zprofile .zshrc)

# Install dotfiles
run_dotfiles() {
  if [ -f "$HOME/.npmrc" ]; then
		e_warning ".npmrc already exists, do it manually"
	else
		cp "$HOME/.dotfiles/.npmrc" ~
		e_success ".npmrc created"
	fi

	for i in "${dotfiles[@]}"; do
    if [ ! -L "$HOME/$i" ] ; then
      if [ -f "$HOME/$i" ]; then
        e_warning "Removing $i"

        rm -rf ~/"$i"
      fi

      ln -s "$HOME/.dotfiles/$i" ~
      e_success "Link to $i created"
    fi
	done

  if [ ! -d "$HOME/.config" ] ; then
    echo "Creating ~/.config"
    mkdir -p "$HOME/.config"
  fi

	for entry in ".config"/*
	do
		if [ ! -L "$HOME/$entry" ] ; then
			echo "Linking $entry"
			ln -s "$HOME/.dotfiles/$entry" "$HOME/.config/"
		fi
	done
}
