#!/usr/bin/env zsh

run_rubygems() {
    e_process "Updating to latest Rubygems version"
    sudo gem update --system

    if [ "$(gem list -i bundler >> /dev/null)" -eq 1 ]; then
    	e_process "Installing Bundler to install project-specific Ruby gems ..."
			gem install bundler --no-document --pre

			e_process "Configuring Bundler for faster, parallel gem installation ..."
			number_of_cores=$(sysctl -n hw.ncpu)
			bundle config --global jobs $((number_of_cores - 1))
    fi

    if [ "$(gem list -i colorls >> /dev/null)" -eq 1 ]; then
    	e_process "Installing colorls"
    	gem install colorls
    fi

    [[ $? ]] && e_success "Done"
}
