tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "melonamin/formulae"
tap "mongodb/brew"
tap "planetscale/tap"
brew "ack"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "gettext"
brew "bfg"
brew "brew-cask-completion"
brew "caddy", restart_service: true
brew "certbot"
brew "cheat"
brew "oniguruma"
brew "php", restart_service: true
brew "composer"
brew "coreutils"
brew "direnv"
brew "docker-clean"
brew "docker-completion"
brew "docker-compose-completion"
brew "docker-machine", restart_service: true
brew "duf"
brew "dust"
brew "exa"
brew "findutils"
brew "fnm"
brew "fzf"
brew "gem-completion"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-filter-repo"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "gping"
brew "grep"
brew "htmlq"
brew "htop"
brew "httpd", restart_service: true
brew "httpie"
brew "hub"
brew "ievms"
brew "python@3.9"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "lame"
brew "launchctl-completion"
brew "libyaml"
brew "mariadb", restart_service: true
brew "mas"
brew "miller"
brew "mkcert"
brew "mongosh"
brew "nginx"
brew "ngrep"
brew "node"
brew "nss"
brew "openssl@3"
brew "pinentry-mac"
brew "procs"
brew "pyenv"
brew "rbenv"
brew "rename"
brew "ripgrep"
brew "rust"
brew "screen"
brew "sd"
brew "speedtest-cli"
brew "thefuck"
brew "tig"
brew "vim"
brew "volta"
brew "watchman"
brew "wget"
brew "yarn"
brew "yarn-completion"
brew "zoxide"
brew "mongodb/brew/mongodb-community"
brew "planetscale/tap/pscale"
cask "1password"
cask "alfred"
cask "arduino"
cask "authy"
cask "battle-net"
cask "browserstacklocal"
cask "coderunner"
cask "colorpicker-materialdesign"
cask "colorpicker-propicker"
cask "colorpicker-skalacolor"
cask "cyberduck"
cask "default-folder-x"
cask "devtoys"
cask "devutils"
cask "discord"
cask "docker"
cask "dropbox"
cask "fig"
cask "firefox"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-inconsolata"
cask "font-ubuntu"
cask "gifox"
cask "github"
cask "gitkraken"
cask "google-chrome"
cask "google-drive"
cask "google-drive-file-stream"
cask "gpg-suite-no-mail"
cask "graphql-playground"
cask "handbrake"
cask "http-toolkit"
cask "iina"
cask "imageoptim"
cask "inkscape"
cask "insomnia"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kitematic"
cask "lastpass"
cask "little-snitch"
cask "macupdater"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "notion"
cask "numi"
cask "obsidian"
cask "pixelsnap"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "quicklook-csv"
cask "quicklook-json"
cask "raycast"
cask "rekordbox"
cask "robo-3t"
cask "rocket"
cask "sequel-pro"
cask "setapp"
cask "sizzy"
cask "slack"
cask "soulver"
cask "spotify"
cask "steam"
cask "suspicious-package"
cask "swiftbar"
cask "the-unarchiver"
cask "tidal"
cask "transmission"
cask "tunnelblick"
cask "typora"
cask "vanilla"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "webcatalog"
cask "whatsapp"
cask "zoom"
mas "CalcService", id: 899970159
mas "Color Picker", id: 1545870783
mas "djay Pro AI", id: 450527929
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Memory Diag", id: 748212890
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Patterns", id: 429449079
mas "Power JSON Editor", id: 499768540
mas "Shazam", id: 897118787
mas "Velja", id: 1607635845
mas "WordService", id: 899972312
mas "Xcode", id: 497799835
