tap "codeclimate/formulae"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "melonamin/formulae"
tap "mongodb/brew"
brew "ack"
brew "python@3.9"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "brew-cask-completion"
brew "caddy", restart_service: true
brew "certbot"
brew "gettext"
brew "oniguruma"
brew "php", restart_service: true
brew "composer"
brew "coreutils"
brew "docker-clean"
brew "docker-machine", restart_service: true
brew "exa"
brew "findutils"
brew "fnm"
brew "fzf"
brew "gem-completion"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "gnupg", link: false
brew "grep"
brew "htop"
brew "httpd", restart_service: true
brew "httpie"
brew "hub"
brew "ievms"
brew "imagemagick"
brew "jq"
brew "lame"
brew "lastpass-cli"
brew "launchctl-completion"
brew "libyaml"
brew "mariadb", restart_service: true
brew "mas"
brew "node@14"
brew "ngrep"
brew "node"
brew "php@7.4"
brew "pinentry-mac"
brew "rename"
brew "ruby"
brew "rust"
brew "screen"
brew "speedtest-cli"
brew "thefuck"
brew "tig"
brew "vim"
brew "volta"
brew "watchman"
brew "wget"
brew "wp-cli"
brew "wp-cli-completion"
brew "yarn"
brew "yarn-completion"
brew "zoxide"
brew "codeclimate/formulae/codeclimate", link: false
brew "mongodb/brew/mongodb-community"
cask "alfred"
cask "arduino"
cask "authy"
cask "battle-net"
cask "calibre"
cask "coderunner"
cask "colorpicker-materialdesign"
cask "colorpicker-propicker"
cask "colorpicker-skalacolor"
cask "cyberduck"
cask "default-folder-x"
cask "discord"
cask "docker"
cask "dropbox"
cask "dynobase"
cask "firefox"
cask "firefox-developer-edition"
cask "font-dejavu-sans"
cask "font-fira-code"
cask "font-inconsolata"
cask "font-inconsolata-dz"
cask "font-source-code-pro"
cask "font-ubuntu"
cask "gather"
cask "gifox"
cask "gitkraken"
cask "google-chrome-canary"
cask "gpg-suite-no-mail"
cask "graphql-playground"
cask "handbrake"
cask "imageoptim"
cask "inkscape"
cask "insomnia"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kitematic"
cask "ksdiff"
cask "little-snitch"
cask "macupdater"
cask "mysqlworkbench"
cask "near-lock"
cask "notion"
cask "numi"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "quicklook-csv"
cask "quicklook-json"
cask "robo-3t"
cask "rocket"
cask "sequel-pro"
cask "slack"
cask "soulver"
cask "spotify"
cask "steam"
cask "suspicious-package"
cask "swiftbar"
cask "the-unarchiver"
cask "transmission"
cask "tunnelblick"
cask "typora"
cask "vanilla"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "CalcService", id: 899970159
mas "Color Picker", id: 1545870783
mas "djay Pro AI", id: 450527929
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Patterns", id: 429449079
mas "Power JSON Editor", id: 499768540
mas "Shazam", id: 897118787
mas "WordService", id: 899972312
mas "Xcode", id: 497799835
