#!/usr/bin/env bash

# Install native apps
run_apps() {

	#utils
	brew cask install alfred
	brew cask install cakebrew
	brew cask install default-folder-x
	brew cask install dropbox
	brew cask install google-drive
	brew cask install istat-menus
	brew cask install launchcontrol
	brew cask install moom
	brew cask install soulver
	brew cask install the-unarchiver
	brew cask install transmission
	brew cask install vlc

	# dev
	brew cask install apikitchen
	brew cask install bettertouchtool
	brew cask install couleurs
	brew cask install cyberduck
	brew cask install dockertoolbox
	brew cask install firefox
	brew cask install github-desktop
	brew cask install google-chrome
	brew cask install imagealpha
	brew cask install imageoptim
	brew cask install jewelrybox
	brew cask install ksdiff # Kaleidoscope command line
	brew cask install macdown
	brew cask install poedit
	brew cask install robomongo
	brew cask install sequel-pro
	#brew cask install sublime-text
	brew cask install textwrangler
	brew cask install totalterminal
	brew cask install vagrant
	brew cask install virtualbox

	# colorpickers
	brew cask install colorpicker-antetype colorpicker-skalacolor colorpicker-propicker
}
