#!/usr/bin/env bash

# Install native apps
run_apps() {
	#utils
	brew cask install alfred
	brew cask install cakebrew
	brew cask install default-folder-x
	brew cask install dropbox
	brew cask install google-drive
	brew cask install istat-menus
	brew cask install launchcontrol
	brew cask install soulver
	brew cask install the-unarchiver
	brew cask install transmission
	brew cask install vlc

	# dev
	brew cask install couleurs
	brew cask install cyberduck
	brew cask install dockertoolbox
	brew cask install firefox
	brew cask install github
	brew cask install google-chrome
	brew cask install hyper
	brew cask install imageoptim
	brew cask install jewelrybox
	brew cask install ksdiff # Kaleidoscope command line
	brew cask install macdown
	brew cask install robo-3t
	brew cask install sequel-pro
	# brew cask install textwrangler
	brew cask install virtualbox
	brew cask install visual-studio-code

	# colorpickers
	brew cask install colorpicker-materialdesign colorpicker-propicker colorpicker-skalacolor
}
