#!/usr/bin/env bash

dotfiles=(.ackrc .aliases .bash_profile .bash_prompt .bashrc .exports .editorconfig .functions .gitattributes .gitconfig .gitignore .inputrc .jscsrc .jshintrc .osx .scss-lint.yml .vim .vimrc)

# Install dotfiles
run_dotfiles() {
	for i in "${dotfiles[@]}"; do
		if [[ "$i" == ".gitconfig" && -f ~/.gitconfig && "$USER" != "gilbarbara" ]]; then
			e_warning ".gitconfig already exists, do it manually"
		else
			rm -rf ~/$i
			ln -s .dotfiles/$i ~
		fi
	done

	source ~/.bash_profile
}
