#!/usr/bin/env bash

dotfiles=(.ackrc .aliases .bash_colors .bash_completion .bash_profile .bash_prompt .bashrc .config .editorconfig .exports .functions .gitattributes .gitconfig .gitignore .inputrc .npmrc .osx .vim .vimrc)

# Install dotfiles
run_dotfiles() {
	for i in "${dotfiles[@]}"; do
		if [[ "$i" == ".gitconfig" && -f ~/.gitconfig && "$USER" != "gilbarbara" ]]; then
			e_warning ".gitconfig already exists, do it manually"
		elif [[ "$i" == ".npmrc" && -f ~/.npmrc && "$USER" != "gilbarbara" ]]; then
			e_warning ".npmrc already exists, do it manually"
		else
			rm -rf ~/"$i"
			ln -s .dotfiles/"$i" ~
		fi
	done

	source ~/.bash_profile
}
