#!/usr/bin/env bash

dotfiles=(.ackrc .aliases .bash_profile .bash_prompt .bashrc .exports .editorconfig .functions .gitattributes .gitconfig .gitignore .inputrc .jscsrc .jshintrc .osx .scss-lint.yml .vim .vimrc)

# Install dotfiles
run_dotfiles() {
	for i in "${dotfiles[@]}"; do
		rm -rf ~/$i
		ln -s .dotfiles/$i ~
	done

	source ~/.bash_profile
}
