#!/usr/bin/env zsh

run_help() {

cat <<EOT


Options:
    -h, --help  Print this help text
    --no-log    Suppress verbose logging
    --no-apps   Suppress application installs
    brew        Install brew packages
    dotfiles    Symlink dotfiles
    npm         Install NPM global packages
    oh-my-zsh   Install oh-my-zsh
    rubygems    Install gems
    structure   Create directory structure
    tools       Install bash tools

Documentation can be found at https://github.com/gilbarbara/dotfiles

EOT
}
