#!/usr/bin/env bash

npm_packages=(
	@sanity/cli
	aws-sam-local
	babel-cli
	babel-preset-env
	babel-preset-react
	babel-preset-stage-0
	babel-register
	bower
	create-react-app
	create-react-native-app
	flow-typed
	github-labels
	gulp
	iectrl
	jscodeshift
	nodemon
	npm-check-updates
	npm-consider
	ntl
	package-size
	pm2
	prettier
	prop-types
	react
	react-dom
	serverless
	react-native-cli
	release
	serve
	source-map-explorer
	surge
	svgo
	tldr
	webpack-bundle-analyzer
	yarn
)

# Install node packages
run_npm() {
	e_process "Getting installed packages"
	packages=$(npm -j -g --depth=0 ls)

	for i in "${npm_packages[@]}"; do
    if [[ $( echo $packages | jq -r '.dependencies."'$i'".version' ) == "null" ]]; then
			e_process "Installing $i"
			npm install -g $i
		else
			e_warning "$i already installed"
		fi
	done
}
