#!/usr/bin/env bash

# Install Quick Look plugins
run_quicklook() {
	brew cask install provisionql
	brew cask install qlcolorcode
	brew cask install qlimagesize
	brew cask install qlmarkdown
	brew cask install qlprettypatch
	brew cask install quicklook-csv
	brew cask install quicklook-json
}
