#!/usr/bin/env bash

# Install Quick Look plugins
run_quicklook() {

	brew cask install qlcolorcode
	#brew cask install qlstephen #broken on Yosemite
	brew cask install qlmarkdown
	brew cask install qlprettypatch
	brew cask install quicklook-csv
	brew cask install quicklook-json
	brew cask install provisionql
}
