#!/usr/bin/env bash

run_rubygems() {
    e_process "Updating to latest Rubygems version ..."
    gem update --system

    e_process "Installing Bundler to install project-specific Ruby gems ..."
    gem install bundler --no-document --pre

    e_process "Configuring Bundler for faster, parallel gem installation ..."
    number_of_cores=$(sysctl -n hw.ncpu)
    bundle config --global jobs $((number_of_cores - 1))

    e_process "Installing utils..."
		gem install colorls
		gem install travis
		gem install wordmove

    [[ $? ]] && e_success "Done"
}
