#!/usr/bin/env bash

export SUBL="${HOME}/Library/Application Support/Sublime Text 3"
export INSTALED_PACKAGES="${SUBL}/Installed Packages"
export SUBL_PACKAGES="${SUBL}/Packages"
export USER_SETTINGS="${SUBL_PACKAGES}/User"

run_sublime() {

	if [ ! -d "${SUBL_PACKAGES}/Package Control" ]; then

		e_process "Installing Package Control"

		mkdir -p "${INSTALED_PACKAGES}"
		mkdir -p "${USER_SETTINGS}"

		curl http://sublime.wbond.net/Package%20Control.sublime-package -o "${INSTALED_PACKAGES}/Package Control.sublime-package"
	fi

	e_process "Setting installed packages"
	cp -fr ./files/sublime/Package\ Control.sublime-settings "${USER_SETTINGS}/Package Control.sublime-settings"

	e_process "Setting Sublime Text User preferences"
	cp -fr ./files/sublime/Preferences.sublime-settings "${USER_SETTINGS}/Preferences.sublime-settings"

	e_process "Installing Snippets"
	mkdir -p "${USER_SETTINGS}/Snippets"
	cp -fr ./files/sublime/snippets/* "${USER_SETTINGS}/Snippets"

}
